services:
  - type: web
    name: 0518-memo
    runtime: node
    repo: https://github.com/hamano4412/0518_memo
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
